Resources:
  HelloBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: efj-site
      WebsiteConfiguration:
        IndexDocument: index.html
  HelloBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket: !Ref HelloBucket
      PolicyDocument:
        Statement:
        - Sid: AllowLambda
          Effect: Allow
          Principal:
            AWS: arn:aws:iam::142362848012:role/lambda-basicauth-exec
          Action:
          - 's3:GetObject*'
          Resource:
          - 'arn:aws:s3:::efj-site/*'
        - Sid: AllowCfront
          Effect: Allow
          Principal:
            CanonicalUser: !GetAtt CFrontOAI.S3CanonicalUserId
          Action:
          - 's3:GetObject'
          Resource:
          - 'arn:aws:s3:::efj-site/*'
  CFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        Enabled: True
        DefaultCacheBehavior:
          ViewerProtocolPolicy: redirect-to-https
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          TargetOriginId: S3-efj-site
        Origins:
          - DomainName: efj-site.s3.amazonaws.com
            Id: S3-efj-site
            S3OriginConfig:
              OriginAccessIdentity: !Join ['', ['origin-access-identity/cloudfront/', !Ref CFrontOAI]]
  CFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'efj-site.s3.amazonaws.com'