Resources:
  HelloBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: efj-site
      WebsiteConfiguration:
        IndexDocument: index.html
  CFront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: index.html
        Enabled: True
        Origins:
          - DomainName: efj-site.s3.amazonaws.com
            Id: S3-efj-site
            S3OriginConfig:
              OriginAccessIdentity: !Join ['', ['origin-access-identity/cloudfront/', !Ref CFrontOAI]]
  CFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'efj-site.s3.amazonaws.com'