name: Deploy Cluster

on: push

jobs:
  cluster:
    name: Deploy stack to AWS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Replace CFN username because I'm lazy
      run: sed -ie s/USERNAME_FROM_GITHUB_SECRET/${{ secrets.SITE_USERNAME }}/ cfn/s3.yaml
    - run: sed -ie s/PASSWORD_FROM_GITHUB_SECRET/${{ secrets.SITE_PASSWORD }}/ cfn/s3.yaml

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Deploy site CFN resources.
      id: efj-mysite
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: bucket
        template: cfn/s3.yaml
        no-fail-on-empty-changeset: "1"

    - name: Deploy static site to S3 bucket
      run: aws s3 sync site/ s3://efj-site/